/* Dependency-free SVG charts. All input remains data, never executable markup. */
(function(){'use strict';const NS='http://www.w3.org/2000/svg',palette=['#7a392b','#4d6d65','#9a7b4e','#65508b'];
const el=(tag,attrs={},text)=>{const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));if(text!=null)n.textContent=text;return n};
const val=v=>typeof v==='number'?v:Number(v); const nice=v=>Number.isFinite(v)?(Math.abs(v)>=1000?Math.round(v).toLocaleString():Number(v.toFixed(2)).toString()):'';
function svgBase(){const svg=el('svg',{viewBox:'0 0 400 220',role:'img'});return svg}
function extent(series,key){const a=series.flatMap(s=>(s.data||[]).map(d=>val(d[key]))).filter(Number.isFinite);return [Math.min(...a),Math.max(...a)]}
function linear(min,max,a,b){if(min===max){min-=1;max+=1}return v=>a+(v-min)*(b-a)/(max-min)}
function axes(svg,xs,ys,xLabel,yLabel){const l=40,t=15;svg.append(el('line',{x1:l,y1:187,x2:390,y2:187,class:'chart-axis'}));svg.append(el('line',{x1:l,y1:t,x2:l,y2:187,class:'chart-axis'}));for(let i=0;i<4;i++){let p=i/3,x=l+p*350,y=187-p*172;svg.append(el('text',{x,y:205,class:'chart-label','text-anchor':'middle'},nice(xs.min+(xs.max-xs.min)*p)));svg.append(el('text',{x:34,y:y+3,class:'chart-label','text-anchor':'end'},nice(ys.min+(ys.max-ys.min)*p)));}if(xLabel)svg.append(el('text',{x:215,y:219,class:'chart-label','text-anchor':'middle'},xLabel));if(yLabel)svg.append(el('text',{x:11,y:102,class:'chart-label',transform:'rotate(-90 11 102)','text-anchor':'middle'},yLabel))}
function cartesian(f){const s=f.series||[],[xmin,xmax]=extent(s,'x'),[ymin,ymax]=extent(s,'y'),x=linear(xmin,xmax,40,390),y=linear(ymin,ymax,187,15),svg=svgBase();axes(svg,{min:xmin,max:xmax},{min:ymin,max:ymax},f.xLabel,f.yLabel);return{svg,s,x,y}}
function line(f){const{svg,s,x,y}=cartesian(f);s.forEach((series,i)=>{const points=(series.data||[]).map(d=>`${x(val(d.x))},${y(val(d.y))}`).join(' ');svg.append(el('polyline',{points,stroke:series.color||palette[i%palette.length],class:'chart-line'}));});return svg}
function scatter(f){const{svg,s,x,y}=cartesian(f);s.forEach((series,i)=>(series.data||[]).forEach(d=>svg.append(el('circle',{cx:x(val(d.x)),cy:y(val(d.y)),r:3.7,fill:series.color||palette[i%palette.length],class:'chart-dot'}))));return svg}
function bar(f){const s=f.series||[],data=s[0]?.data||[],max=Math.max(0,...data.map(d=>val(d.y))),scale=linear(0,max,187,15),svg=svgBase(),w=Math.min(48,310/Math.max(1,data.length));svg.append(el('line',{x1:40,y1:187,x2:390,y2:187,class:'chart-axis'}));data.forEach((d,i)=>{const x=48+i*(330/data.length),y=scale(val(d.y));svg.append(el('rect',{x,y,width:w,height:187-y,fill:s[0]?.color||palette[0]}));svg.append(el('text',{x:x+w/2,y:204,class:'chart-label','text-anchor':'middle'},String(d.x)));});if(f.yLabel)svg.append(el('text',{x:34,y:18,class:'chart-label','text-anchor':'end'},f.yLabel));return svg}
function histogram(f){return bar(f)}
function table(f){const t=document.createElement('table');t.className='chart-table';const h=document.createElement('thead'),hr=document.createElement('tr');(f.columns||[]).forEach(c=>{const th=document.createElement('th');th.textContent=c.label;hr.append(th)});h.append(hr);t.append(h);const b=document.createElement('tbody');(f.rows||[]).forEach(row=>{const tr=document.createElement('tr');(f.columns||[]).forEach(c=>{const td=document.createElement('td'),v=row[c.key];td.textContent=c.format==='number'?nice(val(v)):String(v??'');tr.append(td)});b.append(tr)});t.append(b);return t}
window.MarginCharts={render(f){if(!f||!f.type)return null;if(f.type==='table')return table(f);if(f.type==='bar')return bar(f);if(f.type==='scatter')return scatter(f);if(f.type==='histogram')return histogram(f);return line(f)}}})();
