(() => {'use strict';
  const $ = (s, root=document) => root.querySelector(s);
  const path = location.pathname.replace(/\\/g,'/');
  const isReader = path.endsWith('/article.html');
  const fetchJSON = async url => { const r=await fetch(url); if(!r.ok) throw Error(`${r.status} ${url}`); return r.json(); };
  const text = (node, value) => { node.textContent=value ?? ''; return node; };
  const safeURL = value => { try { const u=new URL(value, location.href); return ['http:','https:','mailto:'].includes(u.protocol) ? u.href : null; } catch { return null; } };
  /* A small allow-list for article body markup. Data authors cannot introduce scripts, handlers, embeds, or unsafe URLs. */
  function safeFragment(html){
    const template=document.createElement('template'); template.innerHTML=String(html||'');
    const allowed=new Set(['EM','STRONG','I','B','A','SUP','SUB','CODE','SPAN','BR','CITE','MATH','MROW','MI','MN','MO','MSUP','MSUB','MFRAC','MSQRT','MTEXT','MSTYLE','MUNDER','MOVER','MUNDOVER']);
    const visit=node=>{[...node.children].forEach(child=>{const tag=child.tagName.toUpperCase();if(!allowed.has(tag)){child.replaceWith(...child.childNodes); return;} [...child.attributes].forEach(a=>{if(tag==='A'&&a.name==='href'){const url=safeURL(a.value);if(url){child.setAttribute('href',url);child.setAttribute('target','_blank');child.setAttribute('rel','noopener');}else child.removeAttribute('href')}else if(!(tag==='SPAN'&&a.name==='class')&&!(tag==='MATH'&&['display','xmlns'].includes(a.name)))child.removeAttribute(a.name)});visit(child)})}; visit(template.content);return template.content;
  }
  function renderCatalogue(catalogue){
    const list=$('#article-list'), input=$('#article-search'), count=$('#catalogue-count'), articles=catalogue.articles||[];
    document.title=`${catalogue.site?.title||'Margin'} — a reading room`;
    const draw=()=>{const q=input.value.trim().toLowerCase(); const matches=articles.filter(a=>[a.title,a.subtitle,a.author,...(a.tags||[])].join(' ').toLowerCase().includes(q));list.replaceChildren();count.textContent=`${matches.length} document${matches.length===1?'':'s'}`;matches.forEach((a,i)=>{const card=document.createElement('a');card.className='article-card';card.href=`article.html?id=${encodeURIComponent(a.id)}`;card.append(text(document.createElement('span'),String(i+1).padStart(2,'0')).classList.add('card-index'));const copy=document.createElement('div'),h=text(document.createElement('h2'),a.title),p=text(document.createElement('p'),a.subtitle||a.summary||'');copy.append(h,p);card.append(copy);const tags=document.createElement('div');tags.className='tags';(a.tags||[]).slice(0,3).forEach(tag=>{const s=text(document.createElement('span'),tag);s.className='tag';tags.append(s)});card.append(tags);list.append(card)});if(!matches.length)list.append(text(document.createElement('p'),'No documents match that search.'));}; input.addEventListener('input',draw);draw();
  }
  const makeGlossary = (root, glossary, onlyTerms) => {
    const terms=Object.entries(glossary||{}).filter(([term])=>!onlyTerms||onlyTerms.some(t=>(typeof t==='string'?t:t.term)===term)).sort((a,b)=>b[0].length-a[0].length); if(!terms.length)return;
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement?.closest('a,button,.glossary-tip')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}); const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
    nodes.forEach(node=>{let value=node.nodeValue, lower=value.toLowerCase(), found=[];terms.forEach(([term,definition])=>{let start=0, needle=term.toLowerCase();while((start=lower.indexOf(needle,start))>-1){const before=lower[start-1],after=lower[start+needle.length];if(!/[\p{L}\p{N}]/u.test(before||'')&&!/[\p{L}\p{N}]/u.test(after||''))found.push({start,end:start+term.length,term,definition});start+=needle.length;}});found.sort((a,b)=>a.start-b.start||b.end-a.end);let end=0,frag=document.createDocumentFragment();found.forEach(m=>{if(m.start<end)return;frag.append(value.slice(end,m.start));const b=document.createElement('button');b.type='button';b.className='glossary';b.setAttribute('aria-label',`${m.term}: ${m.definition}`);b.append(m.term);const tip=text(document.createElement('span'),m.definition);tip.className='glossary-tip';tip.setAttribute('role','tooltip');b.append(tip);b.addEventListener('click',()=>b.classList.toggle('open'));frag.append(b);end=m.end;});if(end){frag.append(value.slice(end));node.replaceWith(frag)}});
  };
  function appendSources(holder, ids, sourceMap){if(!ids?.length)return;const ul=document.createElement('ul');ul.className='note-sources';ids.forEach(id=>{const src=sourceMap.get(id);if(!src)return;const li=document.createElement('li'),a=text(document.createElement('a'),src.label||src.publisher||id),url=safeURL(src.url);if(url){a.href=url;a.target='_blank';a.rel='noopener'}li.append(a);ul.append(li)});holder.append(ul)}
  function renderFigure(figure){const chart=window.MarginCharts?.render(figure);if(!chart)return null;const wrap=document.createElement('figure');wrap.className='chart';if(figure.title)wrap.append(text(document.createElement('h4'),figure.title).classList.add('chart-title'));if(figure.description)wrap.append(text(document.createElement('p'),figure.description).classList.add('chart-description'));if(chart.tagName==='svg'){const label=[figure.title,figure.description].filter(Boolean).join('. ');chart.setAttribute('aria-label',label||'Data chart');chart.setAttribute('tabindex','0')}wrap.append(chart);if(figure.source)wrap.append(text(document.createElement('figcaption'),figure.source));return wrap}
  function renderNote(note, sourceMap){const n=document.createElement('section');n.className=`annotation ${['update','context','original'].includes(note.kind)?note.kind:'context'}`;n.id=note.id?`note-${note.id}`:'';const kind={update:'Updated evidence',context:'Context',original:'Original footnote'}[note.kind]||'Commentary';n.append(text(document.createElement('p'),kind).classList.add('annotation-kicker'));if(note.title)n.append(text(document.createElement('h3'),note.title));if(note.body){const p=document.createElement('p');p.append(safeFragment(note.body));n.append(p)}const fig=renderFigure(note.figure);if(fig)n.append(fig);appendSources(n,note.sourceIds,sourceMap);return n}
  function renderBlock(block, article, sourceMap){const section=document.createElement('section');section.className='article-block';section.dataset.type=block.type||'paragraph';section.id=`block-${block.id}`;if(block.label)section.append(text(document.createElement('p'),block.label).classList.add('block-label'));let content;switch(block.type){case'heading':content=text(document.createElement('h2'),block.text||block.title||'');break;case'image':content=document.createElement('img');content.className='article-image';content.src=safeURL(block.src)||'';content.alt=block.alt||'';section.append(content);if(block.caption)section.append(text(document.createElement('p'),block.caption).classList.add('article-caption'));content=null;break;case'figure':content=renderFigure(block.figure);break;case'equation':content=document.createElement('div');content.className='math';if(block.mathML){content.append(safeFragment(block.mathML))}else text(content,block.text||'');break;case'quote':content=document.createElement('blockquote');content.append(safeFragment(block.html||block.text));break;case'footnote':content=document.createElement('aside');content.className='original-footnote';content.append(safeFragment(block.html||block.text));break;default:content=document.createElement('p');content.append(safeFragment(block.html||block.text));}if(content)section.append(content);if(block.sourceIds?.length){const p=document.createElement('p');p.className='article-caption';p.append('Source: ');block.sourceIds.forEach((id,i)=>{const src=sourceMap.get(id);if(!src)return;if(i)p.append(', ');const a=text(document.createElement('a'),src.label||id),u=safeURL(src.url);if(u){a.href=u;a.target='_blank';a.rel='noopener'}p.append(a)});section.append(p)}if(block.type!=='image')makeGlossary(section,article.glossary,block.glossaryTerms);return section}
  function selectArticle(){return new URLSearchParams(location.search).get('id')||'situational-awareness'}
  async function renderReader(){const status=$('#reader-status'), reader=$('#reader');try{const id=selectArticle(),article=await fetchJSON(`data/${encodeURIComponent(id)}.json`);document.title=`${article.title} — Margin`;text($('#article-kicker'),article.kicker||'Margin / Reader');text($('#article-title'),article.title);text($('#article-dek'),article.dek||article.subtitle||'');text($('#article-meta'),[article.author,article.published&&`Published ${article.published}`,article.updated&&`Reviewed ${article.updated}`].filter(Boolean).join(' · '));const source=$('#source-link');if(article.sourceUrl){source.href=safeURL(article.sourceUrl)||'#'}else source.hidden=true;const context=$('#context-link');context.href=article.context?.downloadUrl||'context/situational-awareness.md';const note=$('#edition-note');if(article.editionNote)text(note,article.editionNote);else note.hidden=true;const sources=new Map((article.sources||[]).map(s=>[s.id,s]));const original=$('#original-column'),margin=$('#margin-column'),chapters=$('#chapter-list');let notes=0;(article.chapters||[]).forEach(ch=>{const li=document.createElement('li'),a=text(document.createElement('a'),ch.title||ch.id);a.href=`#block-${ch.id}`;li.append(a);chapters.append(li)});(article.blocks||[]).forEach(block=>{original.append(renderBlock(block,article,sources));(block.notes||[]).forEach(n=>{margin.append(renderNote(n,sources));notes++})});text($('#note-total'),`(${notes})`);$('#copy-prompt').addEventListener('click',async()=>{const u=new URL(article.context?.promptUrl||'prompts/discuss.md',location.href);try{const prompt=await (await fetch(u)).text();await navigator.clipboard.writeText(`${prompt}\n\nArticle: ${location.href}`)}catch{await navigator.clipboard.writeText(location.href)}const toast=$('#toast-template').content.firstElementChild.cloneNode(true);document.body.append(toast);setTimeout(()=>toast.remove(),2200)});const toggle=$('#mobile-notes');toggle.addEventListener('click',()=>{const show=margin.hasAttribute('hidden');margin.toggleAttribute('hidden',!show);toggle.setAttribute('aria-expanded',String(show))});if(innerWidth<=800)margin.hidden=true;status.remove();reader.hidden=false;const target=location.hash&&$(CSS.escape(location.hash));if(target)setTimeout(()=>target.scrollIntoView(),0)}catch(error){status.textContent='This document could not be opened. Return to the library or check that its data file is present.';console.error(error)}}
  (async()=>{if(isReader)return renderReader();try{renderCatalogue(await fetchJSON('data/articles.json'))}catch(error){$('#article-list').append(text(document.createElement('p'),'The library is being prepared.'));console.error(error)}})();
})();
